SPK_NAME = amule
SPK_VERS = 2.3.1
SPK_REV = 1
SPK_ICON = src/amule.png

DEPENDS  = cross/wxbase cross/zlib cross/$(SPK_NAME)

MAINTAINER = GP
DESCRIPTION = aMule is the all-platform mule client
RELOAD_UI = yes
STARTABLE = no
DISPLAY_NAME = aMule
BETA = 1

HOMEPAGE   = 
LICENSE    =

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh
ADDITIONAL_SCRIPTS =

INSTALL_PREFIX = /usr/local/$(SPK_NAME)

include ../../mk/spksrc.spk.mk
